/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Blender Artist (https://sketchfab.com/moizmuhammad373)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bird-e93a906eb38343c4a14458a637136329
Title: Bird
*/

import * as THREE from "three";
import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations, Clone } from "@react-three/drei";
import { Section, useThreeContext } from "../../context/useThreeContext";

type ActionName = "Scene";
type GLTFActions = Record<ActionName, THREE.AnimationAction>;

interface Props {
  position: THREE.Vector3;
}

const Bird: React.FC<Props> = ({ position }) => {
  const { scene, animations } = useGLTF("/models/birds.glb");
  const { actions } = useAnimations(animations, scene);
  useEffect(() => {
    //@ts-ignore
    actions.Scene.play();
  }, []);
  return (
    <group position={position}>
      <mesh scale={0.2}>
        <boxGeometry></boxGeometry>
      </mesh>
      <primitive object={scene} />
    </group>
  );
};
const Birds: React.FC = () => {
  return (
    <group>
      <Bird position={new THREE.Vector3(0, 0, 0)} />
      <Bird position={new THREE.Vector3(1, 0, 0)} />
    </group>
  );
};

useGLTF.preload("/models/birds.glb");

export default Birds;
